### ISSUE TITLE
Game fails to validate datapack

### ISSUE THREAD

**Issue by dwnsdp** [Ladysnake/Blabber#12]
# Log
```
[17:50:43] [Worker-Main-2/ERROR]: (Blabber) Could not parse dialogue file from dialogue_test:blabber/dialogues/test.json: No key next in MapLike[{"text":"*take sword*"}] missed input: {"end":{"type":"end_dialogue","choices":[{"text":"*take sword*"}],"action":{"type":"blabber:command","value":"/give @s minecraft:iron_sword"}}}
[17:50:43] [Render thread/WARN]: Failed to load level data or datapacks, can't proceed with server load
java.util.concurrent.ExecutionException: java.lang.RuntimeException: No key next in MapLike[{"text":"*take sword*"}] missed input: {"end":{"type":"end_dialogue","choices":[{"text":"*take sword*"}],"action":{"type":"blabber:command","value":"/give @s minecraft:iron_sword"}}}
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[?:?]
	at net.minecraft.class_7196.method_45694(class_7196.java:189) ~[client-intermediary.jar:?]
	at net.minecraft.class_7196.method_41891(class_7196.java:123) ~[client-intermediary.jar:?]
	at net.minecraft.class_7196.method_41899(class_7196.java:202) ~[client-intermediary.jar:?]
	at net.minecraft.class_7196.method_41894(class_7196.java:64) ~[client-intermediary.jar:?]
	at net.minecraft.class_528$class_4272.method_20174(class_528.java:590) ~[client-intermediary.jar:?]
	at net.minecraft.class_528$class_4272.method_20164(class_528.java:480) ~[client-intermediary.jar:?]
	at net.minecraft.class_528$class_4272.method_25402(class_528.java:402) ~[client-intermediary.jar:?]
	at net.minecraft.class_350.method_25402(class_350.java:327) ~[client-intermediary.jar:?]
	at net.minecraft.class_4069.method_25402(class_4069.java:38) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_1611(class_312.java:98) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_25412(class_437.java:409) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_1601(class_312.java:98) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22686(class_312.java:169) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:102) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22684(class_312.java:169) ~[client-intermediary.jar:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) ~[lwjgl-glfw-3.3.1.jar:?]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.1.jar:?]
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474) ~[lwjgl-glfw-3.3.1.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:237) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1244) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[minecraft-1.20.1-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.7.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) ~[NewLaunch.jar:?]
Caused by: java.lang.RuntimeException: No key next in MapLike[{"text":"*take sword*"}] missed input: {"end":{"type":"end_dialogue","choices":[{"text":"*take sword*"}],"action":{"type":"blabber:command","value":"/give @s minecraft:iron_sword"}}}
	at com.mojang.serialization.DataResult.lambda$getOrThrow$5(DataResult.java:101) ~[datafixerupper-6.0.8.jar:?]
	at com.mojang.datafixers.util.Either$Right.map(Either.java:99) ~[datafixerupper-6.0.8.jar:?]
	at com.mojang.serialization.DataResult.getOrThrow(DataResult.java:93) ~[datafixerupper-6.0.8.jar:?]
	at org.ladysnake.blabber.impl.common.DialogueLoader.lambda$load$2(DialogueLoader.java:74) ~[blabber-1.4.3-mc1.20.1-standalone.jar:?]
	at java.util.TreeMap.forEach(TreeMap.java:1282) ~[?:?]
	at org.ladysnake.blabber.impl.common.DialogueLoader.lambda$load$3(DialogueLoader.java:70) ~[blabber-1.4.3-mc1.20.1-standalone.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
[17:50:44] [Worker-Main-11/ERROR]: Couldn't parse element loot_tables:snowyspirit:chests/present_villager
com.google.gson.JsonSyntaxException: Expected name to be an item, was unknown string 'supplementaries:speaker_block'
	at net.minecraft.class_3518.method_17995(class_3518.java:145) ~[client-intermediary.jar:?]
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
	at net.minecraft.class_3518.method_15256(class_3518.java:145) ~[client-intermediary.jar:?]
	at net.minecraft.class_3518.method_15288(class_3518.java:153) ~[client-intermediary.jar:?]
	at net.minecraft.class_77$class_78.method_413(class_77.java:55) ~[client-intermediary.jar:?]
	at net.minecraft.class_77$class_78.method_443(class_77.java:40) ~[client-intermediary.jar:?]
	at net.minecraft.class_85$class_90.method_441(class_85.java:151) ~[client-intermediary.jar:?]
	at net.minecraft.class_85$class_90.method_424(class_85.java:129) ~[client-intermediary.jar:?]
	at net.minecraft.class_79$class_5337.method_29319(class_79.java:86) ~[client-intermediary.jar:?]
	at net.minecraft.class_79$class_5337.method_517(class_79.java:74) ~[client-intermediary.jar:?]
	at net.minecraft.class_5330$class_5333.deserialize(class_5330.java:102) ~[client-intermediary.jar:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76) ~[gson-2.10.jar:?]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40) ~[gson-2.10.jar:?]
	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[gson-2.10.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1214) ~[gson-2.10.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1319) ~[gson-2.10.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1290) ~[gson-2.10.jar:?]
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:179) ~[gson-2.10.jar:?]
	at net.minecraft.class_3518.method_15291(class_3518.java:463) ~[client-intermediary.jar:?]
	at net.minecraft.class_3518.method_15272(class_3518.java:471) ~[client-intermediary.jar:?]
	at net.minecraft.class_55$class_57.method_358(class_55.java:173) ~[client-intermediary.jar:?]
	at net.minecraft.class_55$class_57.deserialize(class_55.java:169) ~[client-intermediary.jar:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76) ~[gson-2.10.jar:?]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40) ~[gson-2.10.jar:?]
	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[gson-2.10.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1214) ~[gson-2.10.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1319) ~[gson-2.10.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1290) ~[gson-2.10.jar:?]
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:179) ~[gson-2.10.jar:?]
	at net.minecraft.class_3518.method_15291(class_3518.java:463) ~[client-intermediary.jar:?]
	at net.minecraft.class_3518.method_15283(class_3518.java:481) ~[client-intermediary.jar:?]
	at net.minecraft.class_52$class_54.method_340(class_52.java:250) ~[client-intermediary.jar:?]
	at net.minecraft.class_52$class_54.deserialize(class_52.java:246) ~[client-intermediary.jar:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76) ~[gson-2.10.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1214) ~[gson-2.10.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1319) ~[gson-2.10.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1261) ~[gson-2.10.jar:?]
	at net.minecraft.class_8490.method_51205(class_8490.java:64) ~[client-intermediary.jar:?]
	at net.minecraft.class_8490.method_51204(class_8490.java:48) ~[client-intermediary.jar:?]
	at net.minecraft.class_60.method_51195(class_60.java:55) ~[client-intermediary.jar:?]
	at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?]
	at net.minecraft.class_60.method_51189(class_60.java:55) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]

```
# json

```
{
  "layout": {
    "type": "blabber:rpg"
  },
  "unskippable": true,
  "start_at": "start",
  "states": {
    "start": {
      "choices": [
        {
          "text": "What have you done with my sword",
          "next": "sword"
        }
      ],
      "text": "I see you've woken, adventurer! I found you in the valley - you've been out since noon yesterday. If you wish to get your wits back together with some training, there's a dummy in the yard."
    },
    "end": {
      "type": "end_dialogue",
      "choices": [
        {
          "text": "*take sword*"
        }
      ],
      "action": {
        "type": "blabber:command",
        "value": "/give @s minecraft:iron_sword"
      }
    },
    "sword": {
      "text": "Don't you worry I have been holding on it.",
      "choices": [
        {
          "text": "*take sword*",
          "next": "end"
        }
      ]
    }
  }
}


```

**Comment by Pyrofab** [comment]
You tried to add a choice to an end state, but end states by definition can't show text. Try removing the `choices` array there.

**Comment by dwnsdp** [comment]
Oh thank you. the Json was created by the online tool though so that may need to be fixed.

**Comment by dwnsdp** [comment]
I believe what may have happened is I had the end state set as the regular type and added a choice before setting it as an end state again.

**Comment by Pyrofab** [comment]
Ah I see, I will try to fix that with the website update
